config/routes.rb
# -*- encoding: utf-8 -*-
Mschool::Application.routes.draw do
  root :to => 'home#index'


  get "report/students", :to => "report#show" , :as => :report
  get "report/students/generate", :to => "report#generate" , :as => :report_generate

  scope(:path_names => { :new => "novo",
                         :edit => "editar"}) do

    resources :students, :path => "alunos"
    resources :teachers, :path => "professores"
    resources :groups, :path => "turmas"
  end




end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name, :subjects_attributes

  has_many :subjects
  has_many :students

  accepts_nested_attributes_for :subjects, :allow_destroy => true


  def self.group_by_teacher_ids(teacher_ids)
    select("groups.id").includes(:subjects)
    .where("subjects.teacher_id in (?)", teacher_ids)
  end

end

app/models/student.rb
# -*- encoding: utf-8 -*-
class Student < ActiveRecord::Base
  attr_accessible :name, :registration, :group_id

  validates_presence_of :name, :message => "Nome é obrigatório"
  validates_presence_of :registration, :message => "Matrícula é obrigatório"

  validates_numericality_of :registration, :message => "Matrícula não é um número", :only_integer => true

  belongs_to :group


  def self.students_grouped_by_group
    includes(:group)
    .all.group_by {|t| t.group.name if t.group}
  end

  def self.students_by_group_name(group_name)
    includes(:group)
    .where("groups.name = ?", group_name)
    .all.group_by {|t| t.group.name}
  end

  def self.students_by_group_ids(group_ids)
    Student.includes(:group)
    .where("groups.id in (?)", group_ids)
    .all.group_by {|t| t.group.name}
  end
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  attr_accessible :group_id, :name, :teacher_id

  belongs_to :group
  belongs_to :teacher
end

app/models/teacher.rb
# -*- encoding: utf-8 -*-
class Teacher < ActiveRecord::Base
  attr_accessible :name

  validates_presence_of :name, :message => "Nome é obrigatório!"

  has_one :subject


  def self.teacher_ids_by_name(teacher_name)
    select(:id).where("name = ?", teacher_name)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = Group.all
  end


  def new
    @group = Group.new
    @subjects = Subject.new
  end

  def create
    @group = Group.new(params[:group])

    if @group.save
      flash[:notice] = "Turma criada com sucesso!"
      redirect_to :action => :index
    else
      render :new
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.delete
    redirect_to groups_path, :notice => "Turma deletada com sucesso!"
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(params[:group])
      redirect_to groups_path, :notice => "Turma editada com sucesso!"
    else
      render :edit
    end
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  def show

  end

  def generate
    students_by_group = Student.students_grouped_by_group

    teacher_name = params[:filter_teacher] || ""
    group_name = params[:filter_group] || ""

    if is_to_filter_by_group_name(group_name)
      students_by_group = Student.students_by_group_name(group_name)
    end

    if is_to_filter_by_teacher_name(teacher_name)
      students_by_group = students_with_filtered_teacher(teacher_name)
    end

    removing_filter_params

    @report = students_by_group

    render :show
  end

  def students_with_filtered_teacher(teacher_name)
    teacher_ids = Teacher.teacher_ids_by_name(teacher_name)
    group_ids = Group.group_by_teacher_ids(teacher_ids)
    Student.students_by_group_ids(group_ids)
  end


  def removing_filter_params
    params[:filter_teacher] = nil;
    params[:filter_group] = nil;
  end

  def is_to_filter_by_group_name(group_name)
    group_name.present?
  end

  def is_to_filter_by_teacher_name(teacher_name)
    teacher_name.present?
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def new
    @student = Student.new
  end

  def index
    @students = Student.all
  end

  def create
    @student = Student.new(params[:student])

    if @student.save
      flash[:notice] = "Aluno criado com sucesso!"
      redirect_to :action => :index
    else
      render :new
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.delete
    redirect_to students_path, :notice => "Aluno deletado com sucesso!"
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update_attributes(params[:student])
      redirect_to students_path, :notice => "Aluno editado com sucesso!"
    else
      render :edit
    end
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController


  def index
    @teachers = Teacher.all
  end

  def new
    @teacher = Teacher.new
  end


  def edit
    @teacher = Teacher.find(params[:id])
  end

  def update
    @teacher = Teacher.find(params[:id])
    if @teacher.update_attributes(params[:teacher])
      redirect_to teachers_path, :notice => "Professor editado com sucesso!"
    else
      render :edit
    end
  end

  def create
    @teacher = Teacher.new(params[:teacher])

    if @teacher.save
      flash[:notice] = "Professor criado com sucesso!"
      redirect_to :action => :index
    else
      render :new
    end
  end

  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.delete
    redirect_to teachers_path, :notice => "Professor deletado com sucesso!"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.erb
<%= nested_form_for @group do |f| %>
  <p>
    <%= f.label :name, "Nome da Turma" %>
    <%= f.text_field :name %>
  </p>

  <%= f.fields_for :subjects do |subjects_form|%>
    <p>
      <%= subjects_form.label :name, "Matéria" %>
      <%= subjects_form.text_field :name, :class => "subject" %>
      <%= subjects_form.link_to_remove "Remover esta matéria" %>
    </p>

    <p>
      <%= subjects_form.label :teacher_id, "Professor" %>
      <%= subjects_form.collection_select :teacher_id, Teacher.all, :id, :name, :include_blank => true %>
    </p>

  <% end %>
  <p>
    <%= f.link_to_add "Adcionar matéria", :subjects, :class => "add_subject", :href => "#"%>
  </p>

  <p class="submit">
    <%= f.submit "Salvar" %>
  </p>
<% end %>

app/views/groups/edit.html.erb
<h1> Editando Turma </h1>

<%= render "form" %>

app/views/groups/index.html.erb
<%= link_to "Cadastrar Turma", new_group_path %>

<table>
  <% if @groups.any? %>
    <tr>
      <td>Nome</td>
    </tr>
      <% @groups.each do |group| %>
        <tr>
          <td><%= group.name %></td>
          <td><%= link_to "Editar", edit_group_path(group.id) %></td>
          <td><%= link_to "Remover", group, :confirm => "Tem certeza?", :method => :delete %></td>
        </tr>
      <% end %>
  <% end %>
</table>

app/views/groups/new.html.erb
<h1> Criando Turma </h1>

<%= render "form" %>

app/views/home/index.html.erb
<%= link_to "Alunos", students_path %>
<%= link_to "Professores", teachers_path %>
<%= link_to "Turmas", groups_path %>
<%= link_to "Relatório", report_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mschool</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "shared/flash_messages" %>
  <%= link_to "Inicio", root_path %>

  <div class="content">
    <section class="main">
       <%= yield %>
    </section>
  </div>

  <%= javascript_include_tag "application" %>
</body>
</html>

app/views/report/show.html.erb
<%= form_tag(report_generate_path, :method => :get) do %>

  <h2>Filtro</h2>
  <p>
    <%= label_tag "Professor" %>
    <%= text_field_tag "filter_teacher" %>
  </p>

  <p>
    <%= label_tag "Turma" %>
    <%= text_field_tag "filter_group" %>
  </p>

  <p>
    <%= submit_tag "Gerar" %>
  </p>
<% end %>

<% if @report %>
  <h1> Relatório Alunos por turma e seus professores</h1>

  <div class= "group">
    <% @report.map do |group, students| %>
      <b><%= label_tag "Turma:" %></b>  <%= group %><br>
      <b>Alunos</b>
      <br/>
      <% students.each do |student| %>
        <div class = "student">
          <%= label_tag "Nome:" %> <%= student.name %><br>
          <%= label_tag "Matricula:" %> <%= student.registration %><br>
          <% @subjects_from_this_group = student.group.subjects  if student.group %>
          <br/>
        </div>
      <% end %>
      <div class = "subjects">
        <b>Disciplinas</b>
        <br/>
        <% if @subjects_from_this_group %>
          <% @subjects_from_this_group.each do |subject| %>
            <%= label_tag "Matéria:" %> <%= subject.name %><br>
            <%= label_tag "Professor:" %> <%= subject.teacher.name %><br>
            <br/>
          <% end %>
        <% end %>
      </div>
      <br/>
    <% end %>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <p class="<%= type %> message">
    <%= message %>
  </p>
<% end %>

app/views/shared/_form_errors.html.erb
<% if record.errors.any? %>
  <div class="form_errors">
    <p>
      Verifique o formulário antes de continuar:
    </p>
    <ul>
      <% record.errors.messages.values.each do |message| %>
        <% message.each do  |msg| %>
          <li><%= msg %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/students/_form.html.erb
<%= render "shared/form_errors", :record => @student %>

<%= form_for @student do |f| %>
  <p>
    <%= f.label :name, "Nome" %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :registration, "Matrícula" %>
    <%= f.text_field :registration %>
  </p>

  <p>
      <%= f.label :group_id, "Turma" %>
      <%= f.collection_select :group_id, Group.all, :id, :name, :include_blank => true %>
  </p>

  <p class="submit">
    <%= f.submit "Salvar" %>
  </p>

<% end %>

app/views/students/edit.html.erb
<h1> Editando Aluno</h1>

<%= render "form" %>

app/views/students/index.html.erb
<%= link_to "Cadastrar Aluno", new_student_path %>


<table>
  <% if @students.any? %>
    <tr>
      <td>Nome</td>
      <td>Matrícula</td>
    </tr>
      <% @students.each do |student| %>
        <tr>
          <td><%= student.name %></td>
          <td><%= student.registration %></td>
          <td><%= link_to "Editar", edit_student_path(student.id) %></td>
          <td><%= link_to "Remover", student, :confirm => "Tem certeza?", :method => :delete %></td>
        </tr>
      <% end %>
  <% end %>
</table>

app/views/students/new.html.erb
<h1> Criando Aluno </h1>

<%= render "form" %>

app/views/teachers/_form.html.erb
<%= render "shared/form_errors", :record => @teacher %>

<%= form_for @teacher do |f| %>
  <p>
    <%= f.label :name, "Nome" %>
    <%= f.text_field :name %>
  </p>

  <p class="submit">
    <%= f.submit "Salvar" %>
  </p>

  <%= link_to "Inicio", root_path %>

<% end %>

app/views/teachers/edit.html.erb
<h1> Editando Professor </h1>

<%= render "form" %>

app/views/teachers/index.html.erb
<%= link_to "Cadastrar Professor", new_teacher_path %>

<table>
  <% if @teachers.any? %>
    <tr>
      <td>Nome</td>
    </tr>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.name %></td>
        <td><%= link_to "Editar", edit_teacher_path(teacher.id) %></td>
        <td><%= link_to "Remover", teacher, :confirm => "Tem certeza?", :method => :delete %></td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/teachers/new.html.erb
<h1> Criando Professor </h1>

<%= render "form" %>